namespace KolejarzCs.Station
{
    enum DecorationTypes
    {
        NUMBER_1 = 1,
        NUMBER_2 = 2,
        NUMBER_3 = 3,
        NUMBER_4 = 4,
        NUMBER_5 = 5,
        NUMBER_6 = 6,
        NUMBER_7 = 7,
        NUMBER_8 = 8,
        NUMBER_9 = 9,

        LETTER_A = -1,
        LETTER_Ą = -2,
        LETTER_B = -3,
        LETTER_C = -4,
        LETTER_Ć = -5,
        LETTER_D = -6,
        LETTER_E = -7,
        LETTER_Ę = -8,
        LETTER_F = -9,
        LETTER_G = -10,
        LETTER_H = -11,
        LETTER_I = -12,
        LETTER_J = -13,
        LETTER_K = -14,
        LETTER_L = -15,
        LETTER_Ł = -16,
        LETTER_M = -17,
        LETTER_N = -18,
        LETTER_Ń = -19,
        LETTER_O = -20,
        LETTER_Ó = -21,
        LETTER_P = -22,
        LETTER_Q = -23,
        LETTER_R = -24,
        LETTER_S = -25,
        LETTER_Ś = -26,
        LETTER_T = -27,
        LETTER_U = -28,
        LETTER_V = -29,
        LETTER_W = -30,
        LETTER_X = -31,
        LETTER_Y = -32,
        LETTER_Z = -33,
        LETTER_Ź = -34,
        LETTER_Ż = -35,

        WATER_TOWER = -36,
        WATER_CRANE = -37,
    }
}
